<template>
    <div id="task-form">
        <form>
            <div class="form-field">
                <div>
                    <label for="name">Name:</label>
                </div>
                <div>
                    <textarea id="name" v-model="name"></textarea>
                </div>
            </div>
            <div class="form-field">
                <label for="case-suite">Case Suite:</label>
                <Multiselect v-model="caseSuite" mode="tags" placeholder="Select options" :searchable="true"
                    :close-on-select="false" :options="caseSuiteOptions" />

            </div>
            <div class="form-field">
                <label for="manual-test-coverage">Manual Test Coverage:</label>
                <select id="manual-test-coverage" v-model="manualTestCoverage">
                    <option disabled value="">Please select one</option>
                    <option v-for="option in manualTestCoverageOptions" :key="option" :value="option">{{ option }}</option>
                </select>
            </div>
            <div class="form-field">
                <div>
                    <label for="pre-condition">Pre-Condition:</label>
                </div>
                <div>
                    <textarea id="pre-condition" v-model="preCondition" rows="3"></textarea>
                </div>
            </div>
            <div class="form-field">
                <div>
                    <label for="test-step">Test Step:</label>
                </div>
                <div>
                    <textarea id="test-step" v-model="testStep" rows="7"></textarea>
                </div>
            </div>
            <div class="form-field">
                <div>
                    <label for="expected-result">Expected Result:</label>
                </div>
                <div>
                    <textarea id="expected-result" v-model="expectedResult" rows="7"></textarea>
                </div>
            </div>
            <div class="form-field">
                <label for="manual-test-environment">Manual Test Environment:</label>
                <select id="manual-test-environment" v-model="manualTestEnvironment">
                    <option disabled value="">Please select one</option>
                    <option v-for="option in manualTestEnvironmentOptions" :key="option" :value="option">{{ option }}
                    </option>
                </select>
            </div>
            <div class="form-field">
                <label for="case-source">Case Source:</label>
                <select id="case-source" v-model="caseSource">
                    <option disabled value="">Please select one</option>
                    <option v-for="option in caseSourceOptions" :key="option" :value="option">{{ option }}</option>
                </select>
            </div>
            <div class="form-field">
                <label for="main-ticket">Main Ticket:</label>
                <input id="main-ticket" type="url" v-model="mainTicket" placeholder="asana defect task url" />
            </div>
            <div class="form-field">
                <label for="generated-by">Generated By:</label>
                <select id="generated-by" v-model="generatedBy">
                    <option disabled value="">Please select one</option>
                    <option v-for="option in generatedByOptions" :key="option" :value="option">{{ option }}</option>
                </select>
            </div>
            <button type="button" @click="createTask">Create</button>
        </form>
    </div>
</template>
  
<script lang="ts">
import { defineComponent, ref, watch } from 'vue';
import Multiselect from '@vueform/multiselect'
import axios from 'axios';

export default defineComponent({
    components: {
        Multiselect
    },
    props: {
        testCase: {
            type: String,
            default: '',
        },
    },
    setup(props) {
        const caseSuite = ref([]);
        const manualTestCoverage = ref('Partial');
        const name = ref('');
        const preCondition = ref('');
        const testStep = ref('');
        const expectedResult = ref('');
        const manualTestEnvironment = ref('STAGE');
        const caseSource = ref('Defect');
        const mainTicket = ref('');
        const generatedBy = ref('gpt-3.5-turbo');

        if (props.testCase.includes('\n\n')) {
            name.value = props.testCase.split('\n\n')[0]?.split('Name: ')[1];
            preCondition.value = props.testCase.split('\n\n')[1].split('Pre-Condition: ')[1];
            testStep.value = props.testCase.split('\n\n')[2].split('Test Step:\n')[1];
            expectedResult.value = props.testCase.split('\n\n')[3].split('Expected Result:\n')[1];
        }

        const caseSuiteOptions = ['即檢及列印', '身分設定', 'SOAP', '下診斷ICD', '藥囑', '醫囑',
            '歷史病歷', '稽核Rule', '報告查詢', '套餐(醫療)', '就診明細', '完成看診', '身體數據', '健保雲端',
            '暫存及存回舊系統', '清空看診資料(病歷維護)', '健保卡及醫事卡', '病患清單', 'Login', 'CPOE',
            '院內公告', '過敏及不良反應', '列印', '問卷', '轉診', 'LifeCycle', '環境設備',
            '手術', '電子表單', '系統交互', '電子病歷', '疫苗', '偕同編輯', '掛號', 'DataSyc', '再次完成看診',
            '癌症相關', '災難復原測試', '架構及技術', '個案管理', '批價帳務', '保險申報', '其他', 'UI'];

        const manualTestCoverageOptions = ['Smoke', 'Quick', 'Partial', 'Full',
            'Backlog', 'DefectVerify', 'FectureVerify', 'E2E', 'Use Case', 'Offline'];

        const manualTestEnvironmentOptions = ['INTT', 'STAGE', 'PROD', 'DEV'];

        const caseSourceOptions = ['PRD', 'Defect', 'Testing', 'ETC', 'CR',
            'E2E', 'Use Case', 'Acceptance Criteria']

        const generatedByOptions = ['Human', 'gpt-3.5-turbo']

        // load saved form data from localStorage on component mount
        const savedData = localStorage.getItem('formData');
        if (savedData) {
            const formData = JSON.parse(savedData);

            name.value = formData.name;
            caseSuite.value = formData.caseSuite;
            manualTestCoverage.value = formData.manualTestCoverage;
            preCondition.value = formData.preCondition;
            testStep.value = formData.testStep;
            expectedResult.value = formData.expectedResult;
            manualTestEnvironment.value = formData.manualTestEnvironment;
            caseSource.value = formData.caseSource;
            mainTicket.value = formData.mainTicket;
            generatedBy.value = formData.generatedBy;
        }


        function createTask() {
            // Implement the logic for creating a task using the form data
            const formDataString = localStorage.getItem('formData');
            if (formDataString) {
                const formData = JSON.parse(formDataString);
                console.log(formData);
                axios.post('http://127.0.0.1:5000/create_task', formData)
                    .then(response => {
                        // Handle response from server
                        // console.log(response.data);
                    })
                    .catch(error => {
                        // Handle error
                        console.log(error);
                    });
            } else {
                console.error("No formData found in localStorage");
            };

        }

        // Watch for changes to reactive properties and update formData real time
        watch([name, caseSuite, manualTestCoverage, preCondition, testStep, expectedResult, manualTestEnvironment, caseSource, mainTicket, generatedBy], () => {
            const updatedFormData = {
                name: name.value,
                caseSuite: caseSuite.value,
                manualTestCoverage: manualTestCoverage.value,
                preCondition: preCondition.value,
                testStep: testStep.value,
                expectedResult: expectedResult.value,
                manualTestEnvironment: manualTestEnvironment.value,
                caseSource: caseSource.value,
                mainTicket: mainTicket.value,
                generatedBy: generatedBy.value,
            };

            localStorage.setItem('formData', JSON.stringify(updatedFormData));
        });

        return {
            name,
            caseSuite,
            manualTestCoverage,
            preCondition,
            expectedResult,
            testStep,
            manualTestEnvironment,
            caseSource,
            mainTicket,
            generatedBy,
            caseSuiteOptions,
            manualTestCoverageOptions,
            manualTestEnvironmentOptions,
            caseSourceOptions,
            generatedByOptions,
            createTask,
        };
    }
})
</script>
<style scoped>
textarea {
    width: 100%;
    white-space: pre-line;
    word-wrap: break-word;
}

input {
    width: 100%;
}

.form-field {
    padding-bottom: 10px;
}
</style>
<style src="@vueform/multiselect/themes/default.css"></style>
